#ifndef SRC_ZCL_ZCL_CUSTOM_ATTR_H_
#define SRC_ZCL_ZCL_CUSTOM_ATTR_H_

/* for electrical measurement cluster */

#define ZCL_ATTRID_CUSTOM_VOLTAGE_MIN       0xF000
#define ZCL_ATTRID_CUSTOM_VOLTAGE_MAX       0xF001
#define ZCL_ATTRID_CUSTOM_CURRENT_MAX       0xF002
#define ZCL_ATTRID_CUSTOM_POWER_MAX         0xF003
#define ZCL_ATTRID_CUSTOM_TIME_RELOAD       0xF004
#define ZCL_ATTRID_CUSTOM_PROTECT_CONTROL   0xF005
#define ZCL_ATTRID_CUSTOM_AUTORESTART       0xF006

#endif /* SRC_ZCL_ZCL_CUSTOM_ATTR_H_ */
